Repository kubecube-io/KubeCube, pull requests merged in 2021-09, with the labels that each got.

#40 add k8s api ExternalResource
  config/crd/bases/extension.kubecube.io_externalresources.yaml
  config/crd/kustomization.yaml
  config/rbac/externalresource_editor_role.yaml
  config/rbac/externalresource_viewer_role.yaml
  config/samples/extension_v1_externalresource.yaml
  pkg/apis/addtoscheme_extension_v1.go
  pkg/apis/extension/v1/externalresource_types.go
  pkg/apis/extension/v1/groupversion_info.go
  pkg/apis/extension/v1/zz_generated.deepcopy.go
  pkg/warden/syncmgr/resources.go
Labels: enhancement

#42 generic auth url add https scheme
  cmd/cube/app/options/flags/auth.go
  pkg/authentication/config.go
  pkg/authentication/identityprovider/generic/generic.go
Labels: ready to merge

#53 add Certified Kubernetes badge
  README.md
Labels: documentation
